# Generated by Django 3.0.2 on 2020-01-07 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_id_collection', '0002_auto_20200107_0745'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_database',
            new_name='user_db',
        ),
    ]
