# Generated by Django 3.0.2 on 2020-01-07 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_id_collection', '0003_auto_20200107_0754'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_db',
            new_name='user_database',
        ),
    ]
