# Generated by Django 3.0.2 on 2020-01-07 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_id_collection', '0004_auto_20200107_0759'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_database',
            new_name='user_db',
        ),
    ]
